### ISSUE TITLE
Error: Cannot find module 'D:\Kuizzy\app.js'

### ISSUE THREAD

**Issue by lexcorp** [KhushrajRathod/Kuizzy#16]
D:\>cd Kuizzy

D:\Kuizzy>dir
 El volumen de la unidad D es Nuevo vol
 El número de serie del volumen es: 2A2F-2CD0

 Directorio de D:\Kuizzy

17/05/2021  08:37 p.m.    <DIR>          .
17/05/2021  08:37 p.m.    <DIR>          ..
07/05/2021  04:22 a.m.               633 .dprintrc.json
07/05/2021  04:22 a.m.    <DIR>          .github
07/05/2021  04:22 a.m.             1,816 .gitignore
07/05/2021  04:22 a.m.             5,906 app.ts
07/05/2021  04:22 a.m.            35,147 LICENSE
07/05/2021  04:22 a.m.               465 package.json
07/05/2021  04:22 a.m.    <DIR>          public
07/05/2021  04:22 a.m.               377 README.md
07/05/2021  04:22 a.m.             6,301 tsconfig.json
07/05/2021  04:22 a.m.            25,412 yarn.lock
               8 archivos         76,057 bytes
               4 dirs   2,862,178,304 bytes libres

D:\Kuizzy>yarn
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

Done in 15.56s.

D:\Kuizzy>yarn start
yarn run v1.22.5
$ node app.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'D:\Kuizzy\app.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)←[39m
←[90m    at internal/main/run_main_module.js:18:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by khrj** [comment]
Hey, I've updated the README instructions - You need to run `yarn build` before `yarn start`
